pipeline:
  name: Spring Petclinic
  identifier: Spring_Petclinic
  projectIdentifier: DavidStewart_Sandbox
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build PetClinic
        identifier: Build_PetClinic
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Rancher_Desktop_K8s
              namespace: build
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: mvn package
                  identifier: mvn_package
                  spec:
                    connectorRef: Unauth_Docker_Hub
                    image: maven:3.8.7-openjdk-18-slim
                    shell: Sh
                    command: |-
                      mvn package -DskipTests
                      echo "Hellooo"
              - step:
                  type: S3Upload
                  name: Upload artifact to S3
                  identifier: S3Upload_1
                  spec:
                    connectorRef: AWS_dstewartharness_private
                    region: us-east-1
                    bucket: dstewart
                    sourcePath: target/spring-petclinic-2.7.3.jar
                    target: petclinicjars
                  when:
                    stageStatus: Success
                    condition: "false"
          caching:
            enabled: false
            paths: []
  properties:
    ci:
      codebase:
        connectorRef: dstewartharnessgh
        repoName: spring-petclinic
        build: <+input>
  notificationRules:
    - name: TestNotify
      identifier: TestNotify
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - <+pipeline.variables.emailAddress>
      enabled: true
