pipeline:
  name: Spring Petclinic
  identifier: Spring_Petclinic
  projectIdentifier: DavidStewart_Sandbox
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dstewartharnessgh
        repoName: spring-petclinic
        build: <+input>
  stages:
    - stage:
        name: Build PetClinic
        identifier: Build_PetClinic
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Colima_K8
              namespace: build
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: mvn package
                  identifier: mvn_package
                  spec:
                    connectorRef: Unauth_Docker_Hub
                    image: maven:3.8.7-openjdk-18-slim
                    shell: Sh
                    command: mvn package -DskipTests -Dmaven.repo.local=/harness/m2
              - step:
                  type: S3Upload
                  name: S3Upload_1
                  identifier: S3Upload_1
                  spec:
                    connectorRef: AWS_dstewartharness_private
                    region: us-east-1
                    bucket: dstewart
                    sourcePath: target/spring-petclinic-2.7.3.jar
                    target: petclinicjars
              - step:
                  type: SaveCacheS3
                  name: SaveCacheS3_1
                  identifier: SaveCacheS3_1
                  spec:
                    connectorRef: AWS_dstewartharness_private
                    region: us-east-1
                    bucket: dstewart
                    key: petclinic
                    sourcePaths:
                      - m2/
                    archiveFormat: Tar
